/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPedidosRouteImport } from './routes/_app.pedidos'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppEntregasRouteImport } from './routes/_app.entregas'
import { Route as AppPedidoIdRouteImport } from './routes/_app.pedido.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidoIdRoute = AppPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/pedidos': typeof AppPedidosRoute
  '/perfil': typeof AppPerfilRoute
  '/pedido/$id': typeof AppPedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/pedidos': typeof AppPedidosRoute
  '/perfil': typeof AppPerfilRoute
  '/pedido/$id': typeof AppPedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pedido/$id': typeof AppPedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/entregas'
    | '/historico'
    | '/pedidos'
    | '/perfil'
    | '/pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entregas'
    | '/historico'
    | '/pedidos'
    | '/perfil'
    | '/pedido/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/entregas'
    | '/_app/historico'
    | '/_app/pedidos'
    | '/_app/perfil'
    | '/_app/pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedido/$id': {
      id: '/_app/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AppPedidoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEntregasRoute: typeof AppEntregasRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPedidoIdRoute: typeof AppPedidoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEntregasRoute: AppEntregasRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPedidoIdRoute: AppPedidoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
